package controller;

/**
 *
 * @author montanajack
 */
public class MemberInformation extends javax.swing.JFrame {

    /** Creates new form ProviderInformation */
    public MemberInformation() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        reportTimespan = new javax.swing.ButtonGroup();
        memberInformationPanel = new javax.swing.JPanel();
        contactInformationLabel = new javax.swing.JLabel();
        contactInformationScrollPane = new javax.swing.JScrollPane();
        contactInformationTextArea = new javax.swing.JTextArea();
        memberIDLabel = new javax.swing.JLabel();
        providerIDValueLabel = new javax.swing.JLabel();
        memberStatusLabel = new javax.swing.JLabel();
        memberStatusValue = new javax.swing.JLabel();
        deleteProviderButton = new javax.swing.JButton();
        editProviderButton = new javax.swing.JButton();
        activateButton = new javax.swing.JButton();
        serviceInformationPanel = new javax.swing.JPanel();
        instanceIDLabel = new javax.swing.JLabel();
        instanceIDValueLabel = new javax.swing.JLabel();
        serviceLabel = new javax.swing.JLabel();
        serviceValueLabel = new javax.swing.JLabel();
        feeLabel = new javax.swing.JLabel();
        feeValueLabel = new javax.swing.JLabel();
        dateProvidedLabel = new javax.swing.JLabel();
        dateProvidedValueLabel = new javax.swing.JLabel();
        billingTimestampLabel = new javax.swing.JLabel();
        billingTimestampValueLabel = new javax.swing.JLabel();
        commentsLabel = new javax.swing.JLabel();
        commentsScrollPane = new javax.swing.JScrollPane();
        commentsTextArea = new javax.swing.JTextArea();
        deleteServiceButton = new javax.swing.JButton();
        editServiceButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        serviceHistoryPanel = new javax.swing.JPanel();
        tableScrollPane = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        fromRadio = new javax.swing.JRadioButton();
        fromTextField = new javax.swing.JTextField();
        toLabel = new javax.swing.JLabel();
        toTextField = new javax.swing.JTextField();
        pastWeekRadio = new javax.swing.JRadioButton();
        entireHistoryRadio = new javax.swing.JRadioButton();
        viewProviderButton = new javax.swing.JButton();
        allProvidersCheckBox = new javax.swing.JCheckBox();
        generateMemberReportButton = new javax.swing.JButton();
        addServiceInstanceButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        memberInformationPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Member Information", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 2, 13))); // NOI18N

        contactInformationLabel.setText("Contact Information:");

        contactInformationTextArea.setColumns(20);
        contactInformationTextArea.setEditable(false);
        contactInformationTextArea.setRows(5);
        contactInformationTextArea.setText("Ambria Taylor\n2323 Western Ave. Apt. 357\nChicago, IL 60615");
        contactInformationScrollPane.setViewportView(contactInformationTextArea);

        memberIDLabel.setText("Member ID:");

        providerIDValueLabel.setText("45");

        memberStatusLabel.setText("Member Status:");

        memberStatusValue.setFont(memberStatusValue.getFont().deriveFont(memberStatusValue.getFont().getStyle() | java.awt.Font.BOLD));
        memberStatusValue.setForeground(new java.awt.Color(204, 0, 0));
        memberStatusValue.setText("Inactive");

        deleteProviderButton.setText("Delete");

        editProviderButton.setText("Edit");

        activateButton.setForeground(new java.awt.Color(0, 153, 0));
        activateButton.setText("Activate");

        org.jdesktop.layout.GroupLayout memberInformationPanelLayout = new org.jdesktop.layout.GroupLayout(memberInformationPanel);
        memberInformationPanel.setLayout(memberInformationPanelLayout);
        memberInformationPanelLayout.setHorizontalGroup(
            memberInformationPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(memberInformationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(memberInformationPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(contactInformationLabel)
                    .add(memberInformationPanelLayout.createSequentialGroup()
                        .add(24, 24, 24)
                        .add(contactInformationScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE))
                    .add(memberInformationPanelLayout.createSequentialGroup()
                        .add(memberInformationPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(memberIDLabel)
                            .add(memberStatusLabel))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(memberInformationPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(providerIDValueLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                            .add(memberStatusValue, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, memberInformationPanelLayout.createSequentialGroup()
                        .add(activateButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(deleteProviderButton)
                        .add(5, 5, 5)
                        .add(editProviderButton)))
                .addContainerGap())
        );

        memberInformationPanelLayout.linkSize(new java.awt.Component[] {activateButton, deleteProviderButton, editProviderButton}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        memberInformationPanelLayout.setVerticalGroup(
            memberInformationPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(memberInformationPanelLayout.createSequentialGroup()
                .add(contactInformationLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(contactInformationScrollPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(memberInformationPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(memberIDLabel)
                    .add(providerIDValueLabel))
                .add(8, 8, 8)
                .add(memberInformationPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(memberStatusLabel)
                    .add(memberStatusValue))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 74, Short.MAX_VALUE)
                .add(memberInformationPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(editProviderButton)
                    .add(deleteProviderButton)
                    .add(activateButton)))
        );

        memberInformationPanelLayout.linkSize(new java.awt.Component[] {activateButton, deleteProviderButton, editProviderButton}, org.jdesktop.layout.GroupLayout.VERTICAL);

        serviceInformationPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Service Information", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 2, 13))); // NOI18N

        instanceIDLabel.setText("Instance ID:");

        instanceIDValueLabel.setText("34");

        serviceLabel.setText("Service:");

        serviceValueLabel.setText("Foot Massage");

        feeLabel.setText("Fee:");

        feeValueLabel.setText("$32.56");

        dateProvidedLabel.setText("Date Provided:");

        dateProvidedValueLabel.setText("10-10-2010");

        billingTimestampLabel.setText("Billing Timestamp:");

        billingTimestampValueLabel.setText("01-31-01 16:56:21");

        commentsLabel.setText("Comments:");

        commentsTextArea.setColumns(20);
        commentsTextArea.setEditable(false);
        commentsTextArea.setRows(5);
        commentsScrollPane.setViewportView(commentsTextArea);

        deleteServiceButton.setText("Delete");
        deleteServiceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteServiceButtonActionPerformed(evt);
            }
        });

        editServiceButton.setText("Edit");
        editServiceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editServiceButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Provider ID:");

        jLabel2.setText("212");

        org.jdesktop.layout.GroupLayout serviceInformationPanelLayout = new org.jdesktop.layout.GroupLayout(serviceInformationPanel);
        serviceInformationPanel.setLayout(serviceInformationPanelLayout);
        serviceInformationPanelLayout.setHorizontalGroup(
            serviceInformationPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, serviceInformationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(serviceInformationPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(serviceInformationPanelLayout.createSequentialGroup()
                        .add(deleteServiceButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(editServiceButton))
                    .add(serviceInformationPanelLayout.createSequentialGroup()
                        .add(serviceInformationPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(dateProvidedLabel)
                            .add(billingTimestampLabel)
                            .add(feeLabel)
                            .add(serviceLabel)
                            .add(instanceIDLabel)
                            .add(commentsLabel))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(serviceInformationPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(serviceValueLabel)
                            .add(feeValueLabel)
                            .add(serviceInformationPanelLayout.createSequentialGroup()
                                .add(serviceInformationPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(billingTimestampValueLabel)
                                    .add(dateProvidedValueLabel))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 191, Short.MAX_VALUE))
                            .add(commentsScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                            .add(serviceInformationPanelLayout.createSequentialGroup()
                                .add(instanceIDValueLabel)
                                .add(106, 106, 106)
                                .add(jLabel1)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel2)))))
                .addContainerGap())
        );
        serviceInformationPanelLayout.setVerticalGroup(
            serviceInformationPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(serviceInformationPanelLayout.createSequentialGroup()
                .add(serviceInformationPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(instanceIDLabel)
                    .add(instanceIDValueLabel)
                    .add(jLabel1)
                    .add(jLabel2))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(serviceInformationPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(serviceLabel)
                    .add(serviceValueLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(serviceInformationPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(serviceInformationPanelLayout.createSequentialGroup()
                        .add(serviceInformationPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(feeLabel)
                            .add(feeValueLabel))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(dateProvidedValueLabel))
                    .add(dateProvidedLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(serviceInformationPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(billingTimestampValueLabel)
                    .add(billingTimestampLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(serviceInformationPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(commentsScrollPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(commentsLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 26, Short.MAX_VALUE)
                .add(serviceInformationPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(editServiceButton)
                    .add(deleteServiceButton)))
        );

        serviceHistoryPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Service History", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 2, 13))); // NOI18N

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Instance ID", "Billing Timestamp", "Date Provided", "Service Name", "Provider Name", "Service Name", "Fee"
            }
        ));
        tableScrollPane.setViewportView(table);

        reportTimespan.add(fromRadio);
        fromRadio.setText("From:");

        fromTextField.setText("01-01-2001");
        fromTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fromTextFieldActionPerformed(evt);
            }
        });

        toLabel.setText("To:");

        toTextField.setText("02-09-2011");
        toTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toTextFieldActionPerformed(evt);
            }
        });

        reportTimespan.add(pastWeekRadio);
        pastWeekRadio.setText("Past Week");
        pastWeekRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pastWeekRadioActionPerformed(evt);
            }
        });

        reportTimespan.add(entireHistoryRadio);
        entireHistoryRadio.setSelected(true);
        entireHistoryRadio.setText("Entire History");
        entireHistoryRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entireHistoryRadioActionPerformed(evt);
            }
        });

        viewProviderButton.setText("View Provider Information");
        viewProviderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewProviderButtonActionPerformed(evt);
            }
        });

        allProvidersCheckBox.setText("All Providers");

        org.jdesktop.layout.GroupLayout serviceHistoryPanelLayout = new org.jdesktop.layout.GroupLayout(serviceHistoryPanel);
        serviceHistoryPanel.setLayout(serviceHistoryPanelLayout);
        serviceHistoryPanelLayout.setHorizontalGroup(
            serviceHistoryPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(serviceHistoryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(serviceHistoryPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(tableScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 895, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, serviceHistoryPanelLayout.createSequentialGroup()
                        .add(8, 8, 8)
                        .add(fromRadio)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(fromTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 97, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(toLabel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(toTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 74, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(pastWeekRadio)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(entireHistoryRadio)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 24, Short.MAX_VALUE)
                        .add(allProvidersCheckBox)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(viewProviderButton)))
                .addContainerGap())
        );

        serviceHistoryPanelLayout.linkSize(new java.awt.Component[] {fromTextField, toTextField}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        serviceHistoryPanelLayout.setVerticalGroup(
            serviceHistoryPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(serviceHistoryPanelLayout.createSequentialGroup()
                .add(tableScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(serviceHistoryPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(serviceHistoryPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(viewProviderButton)
                        .add(allProvidersCheckBox))
                    .add(serviceHistoryPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(fromRadio)
                        .add(fromTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(toLabel)
                        .add(toTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(pastWeekRadio)
                        .add(entireHistoryRadio))))
        );

        generateMemberReportButton.setText("Generate Member Report");

        addServiceInstanceButton.setText("Add Service Instance");
        addServiceInstanceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addServiceInstanceButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, serviceHistoryPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(memberInformationPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(serviceInformationPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(generateMemberReportButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(addServiceInstanceButton)))
                .addContainerGap())
        );

        layout.linkSize(new java.awt.Component[] {addServiceInstanceButton, generateMemberReportButton}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(serviceInformationPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(memberInformationPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(serviceHistoryPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(addServiceInstanceButton)
                    .add(generateMemberReportButton))
                .addContainerGap())
        );

        layout.linkSize(new java.awt.Component[] {memberInformationPanel, serviceInformationPanel}, org.jdesktop.layout.GroupLayout.VERTICAL);

        pack();
    }// </editor-fold>

    private void editServiceButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
    }                                                 

    private void deleteServiceButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        // TODO add your handling code here:
    }                                                   

    private void addServiceInstanceButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                         
        // TODO add your handling code here:
    }                                                        

    private void viewProviderButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
    }                                                

    private void fromTextFieldActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void toTextFieldActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void pastWeekRadioActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void entireHistoryRadioActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        // TODO add your handling code here:
    }                                                  

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
    	Application.setNimbusLookAndFeel();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MemberInformation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton activateButton;
    private javax.swing.JButton addServiceInstanceButton;
    private javax.swing.JCheckBox allProvidersCheckBox;
    private javax.swing.JLabel billingTimestampLabel;
    private javax.swing.JLabel billingTimestampValueLabel;
    private javax.swing.JLabel commentsLabel;
    private javax.swing.JScrollPane commentsScrollPane;
    private javax.swing.JTextArea commentsTextArea;
    private javax.swing.JLabel contactInformationLabel;
    private javax.swing.JScrollPane contactInformationScrollPane;
    private javax.swing.JTextArea contactInformationTextArea;
    private javax.swing.JLabel dateProvidedLabel;
    private javax.swing.JLabel dateProvidedValueLabel;
    private javax.swing.JButton deleteProviderButton;
    private javax.swing.JButton deleteServiceButton;
    private javax.swing.JButton editProviderButton;
    private javax.swing.JButton editServiceButton;
    private javax.swing.JRadioButton entireHistoryRadio;
    private javax.swing.JLabel feeLabel;
    private javax.swing.JLabel feeValueLabel;
    private javax.swing.JRadioButton fromRadio;
    private javax.swing.JTextField fromTextField;
    private javax.swing.JButton generateMemberReportButton;
    private javax.swing.JLabel instanceIDLabel;
    private javax.swing.JLabel instanceIDValueLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel memberIDLabel;
    private javax.swing.JPanel memberInformationPanel;
    private javax.swing.JLabel memberStatusLabel;
    private javax.swing.JLabel memberStatusValue;
    private javax.swing.JRadioButton pastWeekRadio;
    private javax.swing.JLabel providerIDValueLabel;
    private javax.swing.ButtonGroup reportTimespan;
    private javax.swing.JPanel serviceHistoryPanel;
    private javax.swing.JPanel serviceInformationPanel;
    private javax.swing.JLabel serviceLabel;
    private javax.swing.JLabel serviceValueLabel;
    private javax.swing.JTable table;
    private javax.swing.JScrollPane tableScrollPane;
    private javax.swing.JLabel toLabel;
    private javax.swing.JTextField toTextField;
    private javax.swing.JButton viewProviderButton;
    // End of variables declaration

}
